package io.hanko.fidouafclient.client.msg.client

enum class ErrorCode(val id: Short) {

    NO_ERROR(0x00),
    WAIT_USER_ACTION(0x01),
    INSECURE_TRANSPORT(0x02),
    USER_CANCELLED(0x03),
    UNSUPPORTED_VERSION(0x04),
    NO_SUITABLE_AUTHENTICATOR(0x05),
    PROTOCOL_ERROR(0x06),
    UNTRUSTED_FACET_ID(0x07),
    KEY_DISAPPEARED_PERMANENTLY(0x09),
    AUTHENTICATOR_ACCESS_DENIED(0x0c),
    INVALID_TRANSACTION_CONTENT(0x0d),
    USER_NOT_RESPONSIVE(0x0e),
    INSUFFICIENT_AUTHENTICATOR_RESOURCES(0x0f),
    USER_LOCKOUT(0x10),
    USER_NOT_ENROLLED(0x11),
    UNKNOWN(0xFF)
}
